#! /usr/bin/env python3
#searches for a file or folder in ~, case insensitive
#Usage: ./find 'file to search without quotes'
import os, sys
if len(sys.argv) < 2:
	print('Error: Expected atleast 2 arguments, found 1')
	sys.exit()
s = ' '.join(sys.argv[1:])
s = s.lower()
for root, folders, files in os.walk('~'):
	for folder in folders:
		if s in folder.lower():
			print(os.path.join(root,folder))
	for filename in files:
		if s in filename.lower():
			print(os.path.join(root,filename))

