#! /usr/bin/env python3
import sys,bs4,webbrowser,requests
if len(sys.argv) == 1:
	print('google <space> query')
	sys.exit(0)
query = ' '.join(sys.argv[1:])
print('Googling...')
res = requests.get('http://google.com/search?q='+query)
res.raise_for_status()
soup = bs4.BeautifulSoup(res.text,'lxml')
links = soup.select('.r > a')
n = min(4,len(links))
for i in range(n):
	webbrowser.open('http://google.com/'+links[i].get('href'))
